#!/bin/sh
set -eu

DATABASE_PROVISION_ROOT="${DATABASE_PROVISION_ROOT:-/opt/tx-bootstrap/database}"
# shellcheck source=../provision-lib.sh
. "$DATABASE_PROVISION_ROOT/provision-lib.sh"

for name in \
    PARTICIPANT_IDENTITYHUB_DB_NAME \
    PARTICIPANT_IDENTITYHUB_DB_USER \
    PARTICIPANT_IDENTITYHUB_DB_PASSWORD \
    PARTICIPANT_EDC_DB_NAME \
    PARTICIPANT_EDC_DB_USER \
    PARTICIPANT_EDC_DB_PASSWORD \
    PARTICIPANT_PORTAL_DB_NAME \
    PARTICIPANT_PORTAL_OWNER_ROLE \
    PARTICIPANT_PORTAL_MIGRATOR_DB_USER \
    PARTICIPANT_PORTAL_MIGRATOR_DB_PASSWORD \
    PARTICIPANT_PORTAL_DB_ROLE \
    PARTICIPANT_PORTAL_DB_PASSWORD; do
    require_env "$name"
done

ensure_login_role "$PARTICIPANT_IDENTITYHUB_DB_USER" "$PARTICIPANT_IDENTITYHUB_DB_PASSWORD"
ensure_login_role "$PARTICIPANT_EDC_DB_USER" "$PARTICIPANT_EDC_DB_PASSWORD"
ensure_group_role "$PARTICIPANT_PORTAL_OWNER_ROLE"
ensure_login_role "$PARTICIPANT_PORTAL_MIGRATOR_DB_USER" "$PARTICIPANT_PORTAL_MIGRATOR_DB_PASSWORD"
ensure_login_role "$PARTICIPANT_PORTAL_DB_ROLE" "$PARTICIPANT_PORTAL_DB_PASSWORD"
ensure_role_membership "$PARTICIPANT_PORTAL_OWNER_ROLE" "$PARTICIPANT_PORTAL_MIGRATOR_DB_USER"

ensure_database "$PARTICIPANT_IDENTITYHUB_DB_NAME" "$PARTICIPANT_IDENTITYHUB_DB_USER"
ensure_database "$PARTICIPANT_EDC_DB_NAME" "$PARTICIPANT_EDC_DB_USER"
ensure_database "$PARTICIPANT_PORTAL_DB_NAME" "$PARTICIPANT_PORTAL_OWNER_ROLE"

grant_database_connect "$PARTICIPANT_IDENTITYHUB_DB_NAME" "$PARTICIPANT_IDENTITYHUB_DB_USER"
grant_database_connect "$PARTICIPANT_EDC_DB_NAME" "$PARTICIPANT_EDC_DB_USER"
grant_database_connect "$PARTICIPANT_PORTAL_DB_NAME" "$PARTICIPANT_PORTAL_MIGRATOR_DB_USER"
grant_database_connect "$PARTICIPANT_PORTAL_DB_NAME" "$PARTICIPANT_PORTAL_DB_ROLE"

echo "Participant PostgreSQL databases and roles are provisioned."
