name: ${COMPOSE_PROJECT_PREFIX:-tx-bootstrap}-consumer

include:
  - path:
      - ${PARTICIPANT_COMPOSE_REF:-oci://ghcr.io/connected-intelligent-systems/tx-bootstrap-participant:latest}
      - ../vault-bootstrap.compose.yml
      - ../participant-vault.override.yml
      - ../participant-database.override.yml
      - ../participant-auth.override.yml
      - compose.override.yml
    env_file: .env.example
