apiVersion: v2
name: tx-bootstrap-operator
description: Tractus-X operator services for tx-bootstrap
type: application
version: 0.1.4
appVersion: "0.1.4"
kubeVersion: ">=1.27.0-0"
home: https://github.com/connected-intelligent-systems/tx-bootstrap
sources:
  - https://github.com/connected-intelligent-systems/tx-bootstrap
annotations:
  artifacthub.io/license: MIT
