import { useState } from "react";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import {
  Alert,
  AlertTitle,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Stack,
  TextField,
} from "@mui/material";
import type { ParticipantInvite } from "../types";

export function ParticipantInviteDialog({
  invite,
  onClose,
}: {
  invite: ParticipantInvite;
  onClose: () => void;
}) {
  const [copied, setCopied] = useState<"bpn" | "token" | null>(null);
  const [copyFailed, setCopyFailed] = useState<"bpn" | "token" | null>(null);

  async function copyValue(value: string, target: "bpn" | "token") {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(target);
      setCopyFailed(null);
    } catch {
      setCopied(null);
      setCopyFailed(target);
    }
  }

  return (
    <Dialog open onClose={onClose} fullWidth maxWidth="sm">
      <DialogTitle>Participant created</DialogTitle>
      <DialogContent>
        <Stack spacing={2} sx={{ pt: 1 }}>
          <Alert severity="success">
            <AlertTitle>{invite.participant.organization.legalName}</AlertTitle>
            The participant record and onboarding invitation are ready.
          </Alert>
          <Alert severity="warning" variant="outlined">
            Save these participant details now. The registration token may not
            be shown again after this dialog is closed.
          </Alert>
          <Stack direction={{ xs: "column", sm: "row" }} spacing={1}>
            <TextField
              label="Assigned BPN"
              value={invite.participant.bpn.assignedBpn}
              fullWidth
              slotProps={{
                input: { readOnly: true, sx: { fontFamily: "monospace" } },
              }}
              helperText={
                copyFailed === "bpn"
                  ? "Clipboard access failed. Copy the BPN manually."
                  : copied === "bpn"
                    ? "Copied to clipboard."
                    : invite.participant.bpn.source === "LOCAL"
                      ? "Generated by the local BPN registry."
                      : "Existing BPN accepted during participant creation."
              }
            />
            <Button
              startIcon={<ContentCopyIcon />}
              onClick={() =>
                copyValue(invite.participant.bpn.assignedBpn, "bpn")
              }
              sx={{ alignSelf: { sm: "flex-start" }, whiteSpace: "nowrap" }}
            >
              {copied === "bpn" ? "Copied" : "Copy BPN"}
            </Button>
          </Stack>
          <TextField
            label="Registration token"
            value={invite.registrationToken}
            multiline
            minRows={3}
            fullWidth
            slotProps={{
              input: {
                readOnly: true,
                sx: { fontFamily: "monospace", overflowWrap: "anywhere" },
              },
            }}
            helperText={
              copyFailed === "token"
                ? "Clipboard access failed. Select and copy the token manually."
                : copied === "token"
                  ? "Copied to clipboard."
                  : "Share this token securely with the participant."
            }
          />
        </Stack>
      </DialogContent>
      <DialogActions>
        <Button
          onClick={() => copyValue(invite.registrationToken, "token")}
          startIcon={<ContentCopyIcon />}
        >
          {copied === "token" ? "Copied" : "Copy token"}
        </Button>
        <Button variant="contained" onClick={onClose}>
          Done
        </Button>
      </DialogActions>
    </Dialog>
  );
}
