name: ${COMPOSE_PROJECT_PREFIX:-tx-bootstrap}-operator

include:
  - path:
      - ${OPERATOR_COMPOSE_REF:-oci://ghcr.io/connected-intelligent-systems/tx-bootstrap-operator:latest}
      - ../vault-bootstrap.compose.yml
      - database.override.yml
      - compose.override.yml
    env_file: .env.example
