apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tx-bootstrap-operator.componentName" (dict "root" . "component" "identityhub-logging") }}
  labels:
    {{- include "tx-bootstrap-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: issuer-identityhub
data:
  logging.properties: |
    .level=INFO
    org.eclipse.edc.level=INFO
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tx-bootstrap-operator.componentName" (dict "root" . "component" "issuer-did-nginx") }}
  labels:
    {{- include "tx-bootstrap-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: issuer-did
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;

        location /statuslist/ {
            proxy_pass http://{{ include "tx-bootstrap-operator.componentName" (dict "root" . "component" "issuer-service") }}:8088/statuslist/;
            proxy_set_header Host $host;
            proxy_set_header Accept application/json;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/issuance/ {
            proxy_pass http://{{ include "tx-bootstrap-operator.componentName" (dict "root" . "component" "issuer-service") }}:8082/api/issuance/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /.well-known/api/ {
            proxy_pass http://{{ include "tx-bootstrap-operator.componentName" (dict "root" . "component" "issuer-service") }}:8084/.well-known/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/directory/ {
            proxy_pass http://{{ include "tx-bootstrap-operator.componentName" (dict "root" . "component" "bdrs") }}:8082/api/directory/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://{{ include "tx-bootstrap-operator.componentName" (dict "root" . "component" "issuer-service") }}:8083;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
